#ifndef __CONSTANTS_H__
#define __CONSTANTS_H__

#define SCALE_RATIO_BOX2D 32
#define SCALE_RATIO_HANDMADE_Y 32
#define SCALE_RATIO_HANDMADE_X 30
#define MOVETIME 0.3f
#define JOINT_BLOCK_DIST 1.47f
#define JOINT_BLOCK_DIST_NEGATIVE -0.47f

#endif